$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            item:0
        },
        600:{
            items:3
        },
        1000:{
            items:8
        }
    }
})